# 配置dev环境
server:
  port: 7070

spring:
  profiles: dev
  # 指定当前微服务对外暴露的名称
  application:
    name: vireureka-config-client

eureka:
  # 指定eureka服务中心
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
# 配置test环境
server:
  port: 9090

spring:
  profiles: test
  # 指定当前微服务对外暴露的名称
  application:
    name: vireureka-config-client

eureka:
  # 指定eureka服务中心
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
